server.port=8080
server.servlet.context-path=/tracking

spring.datasource.url = jdbc:postgresql://10.1.11.100:9093/tracking
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sql= true

#Redis Conf
spring.data.redis.host=10.1.11.100
spring.data.redis.password=password_new
spring.data.redis.port=6379
spring.data.redis.connect-timeout=1000ms
spring.data.redis.timeout=1000ms
spring.redis.jedis.pool.max-wait=1000ms

#Discovery server conf
eureka.client.service-url.defaultZone=http://10.1.11.100:7070/eureka/
eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
eureka.instance.lease-renewal-interval-in-seconds=25

#Kafka Conf
spring.kafka.bootstrap-servers=10.1.11.100:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
communicate.topics=processing_push_form_submission_data_to_inbox

#kafka topics
kafka.topic.workflow-user-added = user-assignment-to-inbox-user-added
kafka.topic.workflow-user-removed = user-assignment-to-inbox-user-removed

kafka.consumer.group-id=workflow-inbox
kafka.consumer.topics=user-assignment-to-inbox-user-added,user-assignment-to-inbox-user-removed,processing_push_form_submission_data_to_message_box,inboxSentboxFilter-form-data-topic,inbox-sentbox-filter-configuration
kafka.topic.official.intimation=processing_push_form_submission_data_to_message_box
kafka.topic.inboxSentboxFilter=inboxSentboxFilter-form-data-topic
kafka.topic.filter.configuration=inbox-sentbox-filter-configuration

service.filter.config.audit-log-enabled=true